<?php
/** @var $viewModel \Razoyo\CarProfile\ViewModel\MyCarData */
$viewModel = $this->getViewModel();
$availableCars = $viewModel->getAvailableCars();
$customerCarProfile = $viewModel->getCustomerCarProfile();
$makes= $viewModel->getListCarMakes();
$csrfToken = $viewModel->getCsrfToken();
?>
<div class="car-profile-wrapper">
    <div class="car-profile-grid">
        <div class="car-profile-details-column">
            <?php if ($customerCarProfile): ?>
                <div class="car-profile-details">
                    <?php if ($customerCarProfile->getCarImage()): ?>
                        <div class="car-image">
                            <img src="<?= $customerCarProfile->getCarImage() ?>" alt="<?= $customerCarProfile->getCarMake() . ' ' . $customerCarProfile->getCarModel() ?>" />
                        </div>
                    <?php endif; ?>
                    <div class="car-details-grid">
                        <div class="car-detail">
                            <span><?= __('Make: ') ?></span>
                            <span><?= $customerCarProfile->getCarMake() ?></span>
                        </div>
                        <div class="car-detail">
                            <span><?= __('Model: ') ?></span>
                            <span><?= $customerCarProfile->getCarModel() ?></span>
                        </div>
                        <div class="car-detail">
                            <span><?= __('Year: ') ?></span>
                            <span><?= $customerCarProfile->getCarYear() ?></span>
                        </div>
                        <div class="car-detail">
                            <span><?= __('Price: ') ?></span>
                            <span><?= $customerCarProfile->getCarPrice() ?></span>
                        </div>
                        <div class="car-detail">
                            <span><?= __('Seats: ') ?></span>
                            <span><?= $customerCarProfile->getCarSeats() ?></span>
                        </div>
                        <div class="car-detail">
                            <span><?= __('MPG: ') ?></span>
                            <span><?= $customerCarProfile->getCarMpg() ?></span>
                        </div>
                    </div>
                </div>
            <?php else: ?>
                <div class="no-car-profile">
                    <?= __('Select your car:') ?>
                </div>
            <?php endif; ?>
        </div>
        <div class="car-search-column">
            <form action="<?= $viewModel->getSaveActionUrl() ?>" method="post">
                <div class="form-group">
                    <label for="car_make"><?= __('Make') ?></label>
                    <select id="car_make" name="car_make">
                        <option value=""><?= __('All') ?></option>
                        <?php foreach ($makes as $make): ?>
                            <option value="<?= $make ?>"><?= $make ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="form-group">
                    <label for="car_search"><?= __('Search by Make, Model, or Year') ?></label>
                    <select id="car_search" name="car_search"></select>
                </div>
                <input type="hidden" name="car_id" id="car_id">
                <input type="hidden" name="form_key" value="<?= $viewModel->getCsrfToken() ?>" />
                <div class="form-buttons">
                    <button type="submit" class="action primary"><?= __('Save') ?></button>
                </div>
            </form>
        </div>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "carSearchInit": {
                "selector": "#car_search",
                "hiddenInputSelector": "#car_id",
                "сarListApiUrl": "<?= $viewModel->getCarListApiUrl() ?>",
                "options": <?= json_encode($availableCars) ?>
            }
        }
    }
</script>
